openapi: 3.0.1
info:
  title: LATAM Issuing APIs
  description: APIs to VMX Server
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licences/LICENSE-2.0
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /account/balance:
    put:
      tags:
      - Account
      summary: "Cash-in & Cash-out. (VMX Service: M.ASM.MONETARY.ACT, L8V2)"
      description: Credits (cash in) or Debits (cash out) transactions from available
        funds or credit open to buy in an Account
      operationId: Cash-in & Cash-out
      parameters:
      - name: X-ClientID
        in: header
        required: true
        schema:
          type: string
      - name: security-context
        in: header
        required: false
        schema:
          type: string
      - name: username
        in: header
        required: false
        schema:
          type: string
      - name: clientReceivedStartTimestamp
        in: header
        required: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyAccountBalanceRequest'
        required: true
      responses:
        "401":
          description: Unauthorized
        "400":
          description: Bad Request
        "300":
          description: Redirection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
        "405":
          description: Method Not Allowed
        "500":
          description: Backend Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
        "403":
          description: Forbidden
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModifyAccountBalanceResponse'
        "404":
          description: Not Found
      x-proxy-name: Update Balance
      x-group-name: Account
      x-child-product-name: Test
components:
  schemas:
    ModifyAccountBalanceRequest:
      required:
      - accountNumber
      - asmOrganizationNumber
      - representativeId
      type: object
      properties:
        asmOrganizationNumber:
          type: integer
          description: |-
            Length: 3
            Organization Number.

            VisionPLUS Service Data: AZXMAI-ASM-ORG
          format: int32
          example: 809
        representativeId:
          maxLength: 3
          minLength: 1
          type: string
          description: |-
            ID of Representative.

            VisionPLUS Service Data: AZXMAI-ASM-REP
          example: A00
        accountNumber:
          maxLength: 19
          minLength: 19
          type: string
          description: |-
            Length: 19

            Number of Customer's account or card.

            VisionPLUS Service Data: AZXMAI-ACCT-NBR
          example: "4198194069732810121"
        transactionData:
          $ref: '#/components/schemas/ModifyAccountBalanceRequest.TxData'
      description: Modify Account Balance Request
    ModifyAccountBalanceRequest.TxData:
      required:
      - actionCode
      - cardNumber
      - cardSequence
      - description
      - effectiveDate
      - otbUpdateIndicator
      - planNumber
      - planSequence
      - referenceNumber
      - resolutionReferenceNumber
      - storeNumber
      - transactionAmount
      type: object
      properties:
        cardNumber:
          maxLength: 19
          minLength: 12
          type: string
          description: |-
            Length: 19
            Unique identifier or token associated with the card number or payment instrument (FirstVision PAN Token).

            VisionPLUS Service Data: AZXMAI-CARD-NBR
          example: 000540208ID5IXX3865
        cardSequence:
          type: integer
          description: |-
            Card Sequence.

            VisionPLUS Service Data: AZXMAI-CARD-SEQ
          format: int32
          example: 1
        actionCode:
          type: string
          description: |-
            Code that identifies the action to be taken.

            VisionPLUS Service Data: AZXMAI-ACTION-CODE
          example: FUND
        effectiveDate:
          type: string
          description: |-
            Date that specifies when the transaction takes effect in the account.

            VisionPLUS Service Data: AZXMAI-EFF-DATE
          format: date
        transactionAmount:
          type: number
          description: |-
            Length: 11

            Transaction Amount.

            VisionPLUS Service Data: AZXMAI-TXN-AMOUNT
          example: 100
        planNumber:
          type: integer
          description: |-
            Plan Number.

            VisionPLUS Service Data: AZXMAI-PLAN-NBR
          format: int32
          example: 60000
        planSequence:
          type: integer
          description: |-
            Plan Sequence.

            VisionPLUS Service Data: AZXMAI PLAN-SEQ
          format: int32
          example: 1
        storeNumber:
          type: integer
          description: |-
            Store Number.

            VisionPLUS Service Data: AZXMAI-STORE-NBR
          format: int32
          example: 999999998
        authorizationCode:
          maxLength: 6
          minLength: 0
          type: string
          description: |-
            Length: 6

            identifier used to identify the transaction for reconciliation purpose.

            VisionPLUS Service Data: AZXMAI-AUTH-CODE
          example: "123456"
        referenceNumber:
          type: string
          description: |-
            Reference Number.

            VisionPLUS Service Data: AZXMAI-REF-NUM
          example: "12345678901234"
        resolutionReferenceNumber:
          type: string
          description: |-
            Resolution Reference Number For Payments Received For Open Billing Accounts.

            VisionPLUS Service Data: AZXMAI-R-REF-NBR
          example: "123456789012"
        otbUpdateIndicator:
          type: integer
          description: |-
            OTB Update Indicator.

            VisionPLUS Service Data: AZXMAI-OTB-UPDATE-IND
          format: int32
          example: 0
        description:
          type: string
          description: |-
            Length: 40

            Description of the transaction.

            VisionPLUS Service Data: AZXMAI-DESC
          example: Description
        departmentCode:
          type: string
          description: Department Code
          example: PPLD
      description: |-
        Length: 3
        ModifyAccountBalanceRequestTxData
    DResponse:
      type: object
      properties:
        hasError:
          type: boolean
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        data:
          type: object
    Error:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    ModifyAccountBalanceResponse:
      type: object
      properties:
        asmOrganizationNumber:
          type: integer
          description: |-
            Organization number.

            VisionPLUS Service Data: AZXMAO-ACTION-ASM-ORG
          format: int32
        asmRepresentativeId:
          type: string
          description: |-
            Representative id.

            VisionPLUS Service Data: AZXMAO-ACTION-REP
        referralRepresentative:
          type: string
          description: |-
            Referral Representative.

            VisionPLUS Service Data: AZXMAO-REFERRAL-REP
        account:
          $ref: '#/components/schemas/ModifyAccountBalanceResponse.Account'
        foreignUseIndicator:
          type: string
          description: |-
            Foreign use indicator.

            VisionPLUS Service Data: AZXMAO-FOREIGN-USE-IND
        cardNumber:
          type: string
          description: |-
            Unique identifier or token associated with the card number or payment instrument (FirstVision PAN Token).

            VisionPLUS Service Data: AZXMAO-CARD-NBR
          example: 000540208ID5IXX3865
        historyDate:
          type: string
          description: |-
            History date.

            VisionPLUS Service Data: AZXMAO-HIST-DATE
          format: date
        historyTime:
          type: string
          description: |-
            History time.

            VisionPLUS Service Data: AZXMAO-HIST-TIME
        actionCodePri:
          type: integer
          description: |-
            Action code pri.

            VisionPLUS Service Data: AZXMAO-ACTION-CODE-PRI
          format: int32
        recordType:
          type: string
          description: |-
            Record type.

            VisionPLUS Service Data: AZXMAO-RECORD-TYPE
        actionDescription:
          type: string
          description: |-
            Action description.

            VisionPLUS Service Data: AZXMAO-ACTION-DESC
        collectionSequenceNumber:
          type: integer
          description: |-
            Collection sequence number.

            VisionPLUS Service Data: AZXMAO-CTA-SEQ-NBR
          format: int32
        status:
          type: string
          description: |-
            Status.

            VisionPLUS Service Data: AZXMAO-STATUS
        referralAsmOrganization:
          type: integer
          description: |-
            Referral asm organization.

            VisionPLUS Service Data: AZXMAO-REFERRAL-ASM-ORG
          format: int32
        purgeDate:
          type: string
          description: |-
            Purge date.

            VisionPLUS Service Data: AZXMAO-PURGE-DATE
          format: date
        actionDate:
          type: string
          description: |-
            Action date.

            VisionPLUS Service Data: AZXMAO-ACTION-DATE
          format: date
        cardSequence:
          type: integer
          description: |-
            Card sequence.

            VisionPLUS Service Data: AZXMAO-CARD-SEQ
          format: int32
        retention:
          type: string
          description: |-
            Retention.

            VisionPLUS Service Data: AZXMAO-RETENTION
        ctaFile:
          type: string
          description: |-
            CTA file.

            VisionPLUS Service Data: AZXMAO-CTA-FILE
        transactionData:
          $ref: '#/components/schemas/ModifyAccountBalanceResponse.TransactionData'
        letterData:
          $ref: '#/components/schemas/ModifyAccountBalanceResponse.LetterData'
    ModifyAccountBalanceResponse.Account:
      type: object
      properties:
        organizationNumber:
          type: integer
          description: |-
            Organization number.

            VisionPLUS Service Data: AZXMAO-ACCT-ORG
          format: int32
        logo:
          type: integer
          description: |-
            Logo.

            VisionPLUS Service Data: AZXMAO-ACCT-LOGO
          format: int32
        number:
          type: string
          description: |-
            Number.

            VisionPLUS Service Data: AZXMAO-ACCT-NBR
    ModifyAccountBalanceResponse.LetterData:
      type: object
      properties:
        organization:
          type: string
          description: |-
            Organization.

            VisionPLUS Service Data: AZXMAO-LTR-ORG
        code:
          type: string
          description: |-
            Code.

            VisionPLUS Service Data: AZXMAO-LETTER
    ModifyAccountBalanceResponse.TransactionData:
      type: object
      properties:
        currencyData:
          $ref: '#/components/schemas/ModifyAccountBalanceResponse.TransactionData.CurrencyData'
        actionCode:
          type: string
          description: |-
            Action code.

            VisionPLUS Service Data: AZXMAO-ACTION-CODE
        effectiveDate:
          type: string
          description: |-
            Effective date.

            VisionPLUS Service Data: AZXMAO-EFF-DATE
          format: date
        feeAmount:
          type: number
          description: |-
            Fee Amount.

            VisionPLUS Service Data: AZXMAO-FEE-AMT
        transactionCode:
          type: string
          description: |-
            Transaction code.

            VisionPLUS Service Data: AZXMAO-TXN-CODE
        transactionAmount:
          type: number
          description: |-
            Transaction amount.

            VisionPLUS Service Data: AZXMAO-TRAN-AMT
        transactionDescription:
          type: string
          description: |-
            Transaction description.

            VisionPLUS Service Data: AZXMAO-TXN-DESC
        creditLimit:
          type: number
          description: |-
            Credit Limit.

            VisionPLUS Service Data: AZXMAO-CREDIT-LIMIT
        openToBuy:
          type: number
          description: |-
            Open to buy.

            VisionPLUS Service Data: AZXMAO-OPEN-TO-BUY
        cashAvailable:
          type: number
          description: |-
            Cash available.

            VisionPLUS Service Data: AZXMAO-CASH-AVAIL-CR
        planNumber:
          type: string
          description: |-
            Plan number.

            VisionPLUS Service Data: AZXMAO-PLAN-NBR
        currentBalance:
          type: number
          description: |-
            Current balance.

            VisionPLUS Service Data: AZXMAO-CURR-BAL
        planSequence:
          type: integer
          description: |-
            Plan sequence.

            VisionPLUS Service Data: AZXMAO-PLAN-SEQ
          format: int32
        storeNumber:
          type: string
          description: |-
            Store number.

            VisionPLUS Service Data: AZXMAO-STORE-NBR
        departmentCode:
          type: string
          description: |-
            Department code.

            VisionPLUS Service Data: AZXMAO-DEPT-NBR
        authorizationCode:
          type: string
          description: |-
            Authorization code.

            VisionPLUS Service Data: AZXMAO-AUTH-NBR
        stockKeepingUnitNumber:
          type: string
          description: |-
            Stock keeping unit number.

            VisionPLUS Service Data: AZXMAO-SKU-NBR
        salesClerk:
          type: string
          description: |-
            Sales clerk.

            VisionPLUS Service Data: AZXMAO-CLERK
        ticketNumber:
          type: string
          description: |-
            Ticket number.

            VisionPLUS Service Data: AZXMAO-TICKET-NBR
        purchaseOrderNumber:
          type: string
          description: |-
            Purchase order number.

            VisionPLUS Service Data: AZXMAO-PURCHASE-ORDER-NBR
        referenceNumber:
          type: string
          description: |-
            Reference number.

            VisionPLUS Service Data: AZXMAO-REFERENCE-NBR
        insuranceCode:
          type: string
          description: |-
            Insurance code.

            VisionPLUS Service Data: AZXMAO-INS
        reversalDate:
          type: string
          description: |-
            Reversal date.

            VisionPLUS Service Data: AZXMAO-REV-DATE
          format: date
        reversalTime:
          type: string
          description: |-
            Reversal time.

            VisionPLUS Service Data: AZXMAO-REV-TIME
        storeOrganizationNumber:
          type: integer
          description: |-
            Store organization number.

            VisionPLUS Service Data: AZXMAO-STORE-ORG
          format: int32
        approvalIndicator:
          type: string
          description: |-
            Approval indicator.

            VisionPLUS Service Data: AZXMAO-APPR-DECL
        monetaryType:
          type: string
          description: |-
            Monetary type.

            VisionPLUS Service Data: AZXMAO-MON-TYPE
        pointsProgram:
          type: integer
          description: |-
            Points program.

            VisionPLUS Service Data: AZXMAO-PTS-PGM
          format: int32
        pointsAmount:
          type: number
          description: |-
            Points amount.

            VisionPLUS Service Data: AZXMAO-PTS-AMT
        referenceNum:
          type: string
          description: |-
            Reference.

            VisionPLUS Service Data: AZXMAO-R-REF-NBR
        fundCard:
          type: string
          description: |-
            Fund card.

            VisionPLUS Service Data: AZXMAO-PD-FUND-CARD
        fundCardDeclinedReason:
          type: string
          description: |-
            Fund card declined reason.

            VisionPLUS Service Data: AZXMAO-PD-DECL-RSN
        currencyNumber:
          type: string
          description: |-
            Currency number.

            VisionPLUS Service Data: AZXMAO-WALLET
        authorizationNumber:
          type: string
          description: |-
            Authorization number.

            VisionPLUS Service Data: AZXMAO-AUTH-NUMBER
    ModifyAccountBalanceResponse.TransactionData.CurrencyData:
      type: object
      properties:
        currencyCode:
          type: string
          description: |-
            Currency code.

            VisionPLUS Service Data: AZXMAO-CURRENCY-CODE
        currencyNumberOfDecimal:
          type: integer
          description: |-
            Currency number of decimal.

            VisionPLUS Service Data: AZXMAO-CURRENCY-NOD
          format: int32
