openapi: 3.0.1
info:
  title: LATAM Issuing APIs
  description: APIs to VMX Server
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licences/LICENSE-2.0
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /account/walletStatus:
    put:
      tags:
      - Account
      summary: "Account wallet status Update. \n\nVMX Service: M.CMS.WALLET.STATUS.UPD,\
        \ L8V1"
      description: "The Wallet Status Update service enables a user to update the\
        \ status of the wallet occurrences (subsidies) on the wallet record for an\
        \ account.\n \nVMX Service: M.CMS.WALLET.STATUS.UPD, L8V1"
      operationId: Account Wallet Status Update
      parameters:
      - name: X-ClientID
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletStatusUpdateRequest'
        required: true
      responses:
        "422":
          description: |+
            VPL5SWU01E - ORGANIZATION NUMBER MUST BE NUMERIC AND VALID VALUES ARE 001-998

            VPL5SWU02E - CARD NUMBER OR ACCOUNT NUMBER MUST BE PROVIDED

            VPL5SWU03E - ORGANIZATION NOT ON FILE

            VPL5SWU04E - CARD/ACCOUNT NOT VALID FOR ORG

            VPL5SWU05E - CARD/ACCOUNT NOT FOUND ON FILE

            VPL5SWU06E - WALLET RECORD FILE READ ERROR

            VPL5SWU07E - OCCURRENCE MUST BE NUMERIC VALUE 01 TO 30

            VPL5SWU08E - NO WALLET OCCURRENCE ON FILE

            VPL5SWU09E - SUBSIDY CODE INVALID

            VPL5SWU10E - INVALID STATUS VALID VALUES ARE 0 OR 1

            VPL5SWUZ6S - ORGANIZATION NOT ON FILE

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
        "400":
          description: Bad Request
        "405":
          description: Method Not Allowed
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Backend Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
        "300":
          description: Redirection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletStatusUpdateResponse'
      x-proxy-name: Test
      x-group-name: Test
      x-child-product-name: Test
components:
  schemas:
    WalletStatusUpdateRequest:
      required:
      - accountNumber
      - organizationNumber
      - status
      - subsidyCode
      - wallet
      type: object
      properties:
        organizationNumber:
          type: integer
          description: "* Min Length: 1 \n* Max Length: 3 \n\nOrganization Number.\n\
            \nVisionPLUS Service Data: AZXWUI-ORG"
          format: int32
          example: 807
        accountNumber:
          maxLength: 19
          minLength: 19
          type: string
          description: |-
            Card or account number.

            VisionPLUS Service Data: AZXWUI-ACCT-NBR
          example: "4513074002952958903"
        wallet:
          type: integer
          description: "* Min Length: 1 \n* Max Length: 2\n\nOccurrence number of\
            \ the wallet on the wallet record.\n\nVisionPLUS Service Data: AZXWUI-WALLET"
          format: int32
          example: 3
        subsidyCode:
          type: string
          description: "* Min Length: 1 \n* Max Length: 4\n\nCode associated with\
            \ the subsidy (wallet occurrence).\n\nVisionPLUS Service Data: AZXWUI-SUBSIDY-CODE"
          example: C
        status:
          type: integer
          description: "* Min Length: 1\n* Max Length: 1\n\nStatus of the wallet occurrence.\n\
            \ \nValues:\n * 0 = Inactive;\n* 1 = Active;\n* 2 = Suspend;\n* 3 = Manual\
            \ suspend.\n\nVisionPLUS Service Data: AZXWUI-STATUS"
          format: int32
          example: 1
          enum:
          - 0
          - 1
          - 2
          - 3
    DResponse:
      type: object
      properties:
        hasError:
          type: boolean
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        data:
          type: object
    Error:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    WalletStatusUpdateResponse:
      type: object
      properties:
        organizationNumber:
          type: integer
          description: |-
            Max Length: 3

            Organization Number.

            VisionPLUS Service Data: AZXWUO-ORG
          format: int32
          example: 807
        accountNumber:
          type: string
          description: |-
            Max Length: 19

            Account number.

            VisionPLUS Service Data: AZXWUO-CARD-NBR
          example: "4513074002952958903"
