################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
    - title: Introduction
      link: docs/1-introduction.md
    - title: Getting Started
      link: docs/2-getting-started.md
      sections:
        - title: Terminology
          link: docs/getting-started/1-terminology.md
        - title: Postman Tutorial
          link: docs/getting-started/2-postman.md
        - title: Structure
          link: docs/getting-started/3-structure.md
        - title: VMX
          sections:
            - title: Messages List
              link: docs/VMX/messagesList.md
            - title: Functionality List
              link: docs/VMX/functionality_list
        - title: API Reference
          sections:
            - title: Account
              link: docs/api-reference/1-account.md
            - title: Cards
              link: docs/api-reference/2-cards.md
            - title: Customer
              link: docs/api-reference/3-customer.md
            - title: Loyalty
              link: docs/api-reference/4-loyalty.md
            - title: Notifications 
              link: docs/api-reference/5-notifications.md
            - title: Transactions
              link: docs/api-reference/6-transactions.md
            - title: API Request
              link: docs/api-reference/api-request.md 
            - title: Error Response
              link: docs/api-reference/error-response.md
            - title: Error Handling
              link: docs/api-reference/response-handling.md
    - title: Main Cases
      sections:
        - title: API Environment
          link: docs/main-cases/1-api-environment.md
        - title: Upload Founds
          link: docs/main-cases/2-uploads.md
        - title: Card Controls
          link: docs/main-cases/3-card-controls.md
        - title: Relation Client-Account-Card
          link: docs/main-cases/4-relation.md
        - title: Customer Management
          link: docs/main-cases/5-customer.md
        - title: Account Management
          link: docs/main-cases/6-account.md
        - title: Card Management
          link: docs/main-cases/7-card.md
        - title: Card Record
          link: docs/main-cases/8-record.md
        - title: Cash-in/Cash-out
          link: docs/main-cases/9-cash-in-out.md
        - title: Falcon System Integration
          link: docs/main-cases/10-falcon.md
        - title: Digital Card Issuing
          link: docs/main-cases/11-digital.md
        - title: Pan Token
          link: docs/main-cases/12-pan-token.md
        - title: Pin Change
          link: docs/main-cases/13-pin-change.md
        - title: Dynamic CVV2
          link: docs/main-cases/14-dynamic.md
        - title: Audit and Monitoring
          link: docs/main-cases/15-audit.md
        - title: HMAC Signature
          link: docs/main-cases/16-hmac.md
    - title: Release Notes
      link: docs/release-notes.md
