################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
    - title: English
      sections:
        - title: Introduction
          link: docs/english/introduction.md
        - title: Getting Started
          link: docs/english/getting-started.md
          sections:
            - title: Postman Tutorial
              link: docs/english/getting-started/postman.md
            - title: Structure
              link: docs/english/getting-started/structure.md
            - title: Terminology
              link: docs/english/getting-started/terminology.md
            - title: VMX Messages List
              link: docs/english/getting-started/messages-list.md
        - title: API Reference
          sections:
            - title: Account
              link: docs/english/api-reference/1-account.md
            - title: Cards
              link: docs/english/api-reference/2-cards.md
            - title: Customer
              link: docs/english/api-reference/3-customer.md
            - title: Loyalty
              link: docs/english/api-reference/4-loyalty.md
            - title: Notifications 
              link: docs/english/api-reference/5-notifications.md
            - title: Transactions
              link: docs/english/api-reference/6-transactions.md
            - title: API Glossary
              link: docs/english/api-reference/api-glossary.md
            - title: API Request
              link: docs/english/api-reference/api-request.md
            - title: Error Handling
              link: docs/english/api-reference/response-handling.md
            - title: Error Response
              link: docs/english/api-reference/error-response.md
        - title: Main Cases
          sections:
            - title: Account Management
              link: docs/english/main-cases/account.md
            - title: API Environment
              link: docs/english/main-cases/api-environment.md
            - title: Audit and Monitoring
              link: docs/english/main-cases/audit.md
            - title: Card Controls
              link: docs/english/main-cases/card-controls.md
            - title: Card Management
              link: docs/english/main-cases/card.md
            - title: Customer Management
              link: docs/english/main-cases/customer.md
            - title: Digital Card Issuing
              link: docs/english/main-cases/digital.md		  
            - title: Dynamic CVV2
              link: docs/english/main-cases/dynamic.md
            - title: Falcon System Integration
              link: docs/english/main-cases/falcon.md
            - title: HMAC Signature
              link: docs/english/main-cases/hmac.md
            - title: PAN Token
              link: docs/english/main-cases/pan-token.md	  
            - title: Relation Client-Account-Card
              link: docs/english/main-cases/relation.md
            - title: Upload Founds
              link: docs/english/main-cases/uploads.md
        - title: Release Notes
          link: docs/english/release-notes.md
    - title: Español
      sections:
        - title: Introducción
          link: docs/spanish/introduccion.md
        - title: Empezando
          link: docs/spanish/empezando.md
          sections:
            - title: Estructura
              link: docs/spanish/empezando/estructura.md
            - title: Lista de Servicios
              link: docs/spanish/empezando/lista-servicios.md
            - title: Postman
              link: docs/spanish/empezando/postman.md			  
            - title: Terminología
              link: docs/spanish/empezando/terminologia.md
        - title: Referencia API
          sections:
            - title: Clientes
              link: docs/spanish/referencia-api/1-clientes.md
            - title: Cuentas
              link: docs/spanish/referencia-api/2-cuentas.md
            - title: Lealtad
              link: docs/spanish/referencia-api/3-lealtad.md
            - title: Notificaciones
              link: docs/spanish/referencia-api/4-notificaciones.md
            - title: Tarjetas 
              link: docs/spanish/referencia-api/5-tarjetas.md
            - title: Transacciones
              link: docs/spanish/referencia-api/6-transacciones.md
            - title: Glosario API
              link: docs/spanish/referencia-api/glosario-api.md
            - title: Manejo de Respuesta
              link: docs/spanish/referencia-api/manejo-respuesta.md
            - title: Respuesta de Error
              link: docs/spanish/referencia-api/respuesta-error.md
            - title: Solicitud de API
              link: docs/spanish/referencia-api/solicitud-api.md
        - title: Casos Principales
          sections:
            - title: Ambiente de API
              link: docs/spanish/casos-principales/ambiente-api.md
            - title: Auditoría y Monitoreo
              link: docs/spanish/casos-principales/auditoria.md
            - title: Cargar Fondos
              link: docs/spanish/casos-principales/cargas.md
            - title: Controles de Tarjetas
              link: docs/spanish/casos-principales/controles-tarjeta.md
            - title: CVV2 Dinámico
              link: docs/spanish/casos-principales/cvv-dinamico.md
            - title: Emisión de Tarjetas Digitales
              link: docs/spanish/casos-principales/emision-tarjetas.md
            - title: Gestión de Clientes
              link: docs/spanish/casos-principales/gestion-clientes.md
            - title: Gestión de Cuentas
              link: docs/spanish/casos-principales/gestion-cuentas.md
            - title: Gestión de Tarjetas
              link: docs/spanish/casos-principales/gestion-tarjetas.md
            - title: HMAC Signature
              link: docs/spanish/casos-principales/hmac.md
            - title: Integración con el Sistema Falcon
              link: docs/spanish/casos-principales/integracion-falcon.md
            - title: PAN Token
              link: docs/spanish/casos-principales/pan-token.md  
            - title: Relación Cliente-Cuenta-Tarjeta
              link: docs/spanish/casos-principales/relacion.md
        - title: Release Notes
          link: docs/spanish/release-notes.md
