---
- sections:
    - title: Getting Started
      link: docs/english/getting-started.md
- sections:
    - title: English
      sections:
        - title: Introduction
          link: docs/english/introduction.md
          sections:
            - title: Postman Tutorial
              link: docs/english/getting-started/postman.md
            - title: Services List
              link: docs/english/getting-started/messages-list.md
            - title: Structure
              link: docs/english/getting-started/structure.md
            - title: Terminology
              link: docs/english/getting-started/terminology.md
        - title: API Reference
          link: docs/english/api-reference/api-reference.md
          sections:
            - title: Account
              link: docs/english/api-reference/1-account.md
            - title: Cards
              link: docs/english/api-reference/2-cards.md
            - title: Customer
              link: docs/english/api-reference/3-customer.md
            - title: Loyalty
              link: docs/english/api-reference/4-loyalty.md
            - title: Notifications
              link: docs/english/api-reference/5-notifications.md
            - title: Transactions
              link: docs/english/api-reference/6-transactions.md
            - title: API Glossary
              link: docs/english/api-reference/api-glossary.md
            - title: API Request
              link: docs/english/api-reference/api-request.md
            - title: Error Handling
              link: docs/english/api-reference/response-handling.md
            - title: Error Response
              link: docs/english/api-reference/error-response.md
        - title: Main Cases
          sections:
            - title: Account Management
              link: docs/english/main-cases/account.md
            - title: API Environment
              link: docs/english/main-cases/api-environment.md
            - title: Audit and Monitoring
              link: docs/english/main-cases/audit.md
            - title: Card Controls
              link: docs/english/main-cases/card-controls.md
            - title: Card Management
              link: docs/english/main-cases/card.md
            - title: Customer Management
              link: docs/english/main-cases/customer.md
            - title: Digital Card Issuing
              link: docs/english/main-cases/digital.md
            - title: Falcon System Integration
              link: docs/english/main-cases/falcon.md
            - title: HMAC Signature
              link: docs/english/main-cases/hmac.md
            - title: Relation Client-Account-Card
              link: docs/english/main-cases/relation.md
            - title: Upload Founds
              link: docs/english/main-cases/uploads.md
        - title: Release Notes
          sections:
            - title: 2023
              link: docs/português/releaseNotes/2023.md
            - title: 2024
              link: docs/português/releaseNotes/2024.md
    - title: Español
      sections:
        - title: Introducción
          link: docs/spanish/introduccion.md
        - title: Empezando
          link: docs/spanish/empezando.md
          sections:
            - title: Estructura
              link: docs/spanish/empezando/estructura.md
            - title: Lista de Servicios
              link: docs/spanish/empezando/lista-servicios.md
            - title: Postman
              link: docs/spanish/empezando/postman.md
            - title: Terminología
              link: docs/spanish/empezando/terminologia.md
        - title: Referencia API
          sections:
            - title: Clientes
              link: docs/spanish/referencia-api/1-clientes.md
            - title: Cuentas
              link: docs/spanish/referencia-api/2-cuentas.md
            - title: Lealtad
              link: docs/spanish/referencia-api/3-lealtad.md
            - title: Notificaciones
              link: docs/spanish/referencia-api/4-notificaciones.md
            - title: Tarjetas
              link: docs/spanish/referencia-api/5-tarjetas.md
            - title: Transacciones
              link: docs/spanish/referencia-api/6-transacciones.md
            - title: Glosario API
              link: docs/spanish/referencia-api/glosario-api.md
            - title: Manejo de Respuesta
              link: docs/spanish/referencia-api/manejo-respuesta.md
            - title: Respuesta de Error
              link: docs/spanish/referencia-api/respuesta-error.md
            - title: Solicitud de API
              link: docs/spanish/referencia-api/solicitud-api.md
        - title: Casos Principales
          sections:
            - title: Ambiente de API
              link: docs/spanish/casos-principales/ambiente-api.md
            - title: Auditoría y Monitoreo
              link: docs/spanish/casos-principales/auditoria.md
            - title: Cargar Fondos
              link: docs/spanish/casos-principales/cargas.md
            - title: Controles de Tarjetas
              link: docs/spanish/casos-principales/controles-tarjeta.md
            - title: Emisión de Tarjetas Digitales
              link: docs/spanish/casos-principales/emision-tarjetas.md
            - title: Firma HMAC
              link: docs/spanish/casos-principales/hmac.md
            - title: Gestión de Clientes
              link: docs/spanish/casos-principales/gestion-clientes.md
            - title: Gestión de Cuentas
              link: docs/spanish/casos-principales/gestion-cuentas.md
            - title: Gestión de Tarjetas
              link: docs/spanish/casos-principales/gestion-tarjetas.md
            - title: Integración con el Sistema Falcon
              link: docs/spanish/casos-principales/integracion-falcon.md
            - title: Relación Cliente-Cuenta-Tarjeta
              link: docs/spanish/casos-principales/relacion.md
        - title: Release Notes
          sections:
            - title: 2023
              link: docs/português/releaseNotes/2023.md
            - title: 2024
              link: docs/português/releaseNotes/2024.md
    - title: Português
      sections:
        - title: Introdução
          link: docs/português/introdução.md
        - title: Começando
          link: docs/português/começando.md
          sections:
            - title: Estrutura
              link: docs/português/começando/estrutura.md
            - title: Lista de Serviços
              link: docs/português/começando/lista-serviços.md
            - title: Postman
              link: docs/português/começando/postman.md
            - title: Terminologia
              link: docs/português/começando/terminologia.md
        - title: Referência API
          sections:
            - title: Cartões
              link: docs/português/referência-api/1-cartões.md
            - title: Cliente
              link: docs/português/referência-api/2-cliente.md
            - title: Conta
              link: docs/português/referência-api/3-conta.md
            - title: Fidelidade
              link: docs/português/referência-api/4-fidelidade.md
            - title: Notificações
              link: docs/português/referência-api/5-notificações.md
            - title: Transações
              link: docs/português/referência-api/6-transações.md
            - title: Gestão de Resposta
              link: docs/português/referência-api/gestão-resposta.md
            - title: Glossário da API
              link: docs/português/referência-api/glossário-api.md
            - title: Resposta de Erro
              link: docs/português/referência-api/resposta-erro.md
            - title: Solicitação de API
              link: docs/português/referência-api/solicitação-api.md
        - title: Principais Casos
          sections:
            - title: Ambiente da API
              link: docs/português/principais-casos/ambiente-api.md
            - title: Assinatura HMAC 
              link: docs/português/principais-casos/hmac.md
            - title: Auditoria e Monitoramento
              link: docs/português/principais-casos/auditoria.md
            - title: Carregar Fundos
              link: docs/português/principais-casos/carregar-fundos.md
            - title: Controles de Cartão
              link: docs/português/principais-casos/controles-cartão.md
            - title: Emissão de Cartões Digitais
              link: docs/português/principais-casos/emissão-cartões.md
            - title: Gestão de Cartões
              link: docs/português/principais-casos/gestão-cartões.md
            - title: Gestão de Clientes
              link: docs/português/principais-casos/gestão-clientes.md
            - title: Gestão de Contas
              link: docs/português/principais-casos/gestão-contas.md
            - title: Integração com o Sistema Falcon
              link: docs/português/principais-casos/integração-falcon.md
            - title: Relação Cliente-Conta-Cartão
              link: docs/português/principais-casos/relação.md
        - title: Release Notes
          sections:
            - title: 2023
              link: docs/português/releaseNotes/2023.md
            - title: 2024
              link: docs/português/releaseNotes/2024.md
