################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: FirstVision - LATAM
  productionDescription: Expand your business’ reach by taking the acceptance process to a different level.
  whoIsItFor: LATAM
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: FirstVision - LATAM™
steps:  
  learnSteps:
    - title: Learn
      description: >
        Follow our documentation and easy to use examples to build your own mobile or web integrated online applications. 
      link:
  buildSteps:
    - title: Build
      description: >
        Get your application up and running with our proprietary integration tools and developer keys. 
      link:
  validateSteps:
    - title: API Explorer
      description: >
        Interact with our live api interface for real time responses to the developed application. 
      link:
  deploySteps:
    - title: Deploy
      description: >
        Deploy your applications in our testing environment for quality assurance testing.  Once ready promote your application to our production environment. 
      link:
featuredFeatures:
  - title: Credit Issuance
    description:  FirstVision solution allows financial Institution to issue and manage the Credit Card products to their end customers. 
    tags: ["LATAM", "FirstVision", "Credit"]
    bullets: ["Activate Card", "Block Card", "Lost Stolen Card Transfer", "CVV2 Validation" ]  
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/used.
        link: ./docs/api-reference/1-account.md
      - relatedDoc: 
        title: Cards Management
        description: Allows management of payment instrument that is used to perform financial transaction such as physical Card, Virtual Card, Wallet Token. 
        link: ./docs/api-reference/2-cards.md
      - relatedDoc: 
        title: Customer Management
        description: Allows management of a cardholder's demographic information like Name, Address, phone numbers, etc.  
        link: ./docs/api-reference/3-customer.md
      - relatedDoc: 
        title: Loyalty Management
        description: Allows management of loyalty programs like points adjusment.
        link: ./docs/api-reference/4-loyalty.md
      - relatedDoc: 
        title: Notifications Management
        description: Allows management of events for enrollment and cancellation.
        link: ./docs/api-reference/5-notifications.md
      - relatedDoc: 
        title: Transactions Management
        description: Allows management of transactions such as details, exchange rate, etc.
        link: ./docs/api-reference/6-transactions.md
    relatedAPIs:
      - relatedAPI: 
        title: Cash-in & Cash-out.
        description: Credits (cash in) or Debits (cash out) transactions from available funds or credit open to buy in an Account
        type: "put"
        path: "/account/balance"
      - relatedAPI:
        title: Card Activation
        description: Activate Card.
        type: "put"
        path: "/cards/activation"
      - relatedAPI: 
        title: Update Customer
        description: Customer Update
        type: "put"
        path: "/customer"
      - relatedAPI: 
        title: Inquire or Update Exchange Rate
        description: Inquire or Update Exchange Rate
        type: "put"
        path: "/transactions/exchange-rate"
      - relatedAPI: 
        title: pointsDisbursement
        description: TLMS Points Account Auto Disbursement Data Update. 
        type: "put"
        path: "/loyalty/pointsDisbursement"
