################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: FirstVision - LATAM
  productionDescription: Fiserv provides a single, consolidated processing platform for all your payment cards, loans, prepaid, and commercial card products. FirstVision™ is our outsourced processing solution that meets your challenges head-on and transforms your technology capability. Built on core VisionPLUS® software, FirstVision™ provides an end-to-end solution. FirstVision™ Restful APIs enable you to achieve platform modernization and competitive edge delivering the following benefits to your business.
  getStarted: docs/english/getting-started.md
  whoIsItFor: LATAM
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: FirstVision - LATAM™
benefits:
  - title: Time to Market
    description: Service-based architecture with API enabled and a fully integrated suite of solutions ensures quicker application development and integration.
  - title: Transform Business
    description: Platform architecture built around technology simplification and leveraging open APIs, reducing the cost of change and meeting the innovation.
  - title: Speed to Market
    description: FirstVision™ oriented architecture with open APIs enables service consumption rather than change management.
featuredFeatures:
  - title: Accounts
    description: Account basic functions such as add, inquiry and edit account. Also includes account level processing options for a card account.
    featured: true
    relatedDocs:
    - link: docs/english/api-reference/1-account.md
      title: Accounts
    relatedAPIs:
    - title: Accound Add
      type: "post"
      path: "/account/add-L8V3"
  - title: Cards
    description: Cards functions to add, inquiry and edit card records. A card record contains information about the card (or “plastic”) that is issued to the cardholder. Also includes cross reference between customer, account and card.
    featured: true
    relatedDocs:
    - link: docs/english/api-reference/2-cards.md
      title: Cards
    relatedAPIs:
    - title: Card Activation
      type: "put"
      path: "/cards/activation"
  - title: Customer
    description: Customer Name Address functions. Multiple accounts can be associated with a single Customer Name/Address record. Cross-reference between records customer to account to cards and relationships are also available.
    featured: true
    relatedDocs:
    - link: docs/english/api-reference/3-customer.md
      title: Customer
    relatedAPIs:
    - title: Account Number Inquiry
      type: "post"
      path: "/customer/accountNumber"
  - title: Transactions
    description: Transactions functions to add, adjust or inquiry functions actions. Display transactional details such as outstanding authorizations, cycle-to-date, memo-posted, warehoused, disputed transactions, exchange rate, installment data, transaction details and processing control inquiry.
    featured: true
    relatedDocs:
    - link: docs/english/api-reference/5-transactions.md
      title: Transactions
    relatedAPIs:
    - title: Account Enrollment Inquiry
      type: "get"
      path: "/transactions/enroll-history/{accountNumber}"
