components:
  schemas:
    DResponse:
      properties:
        data:
          type: object
        errors:
          items:
            $ref: '#/components/schemas/Error'
          type: array
        hasError:
          type: boolean
      type: object
    Error:
      properties:
        code:
          type: string
        description:
          type: string
      type: object
    OutstandingAuthorizationFasRequest:
      description: Outstanding Authorizations Request
      properties:
        accountNumber:
          description: 'Length: 19

            Account Number

            VisionPLUS Service Data: OZXOAI-ACCT'
          example: '4513074002573466583'
          maxLength: 19
          maximum: 19
          minLength: 19
          minimum: 19
          type: string
        authorizationDateRange:
          $ref: '#/components/schemas/OutstandingAuthorizationFasRequest.AuthorizationDateRange'
        authorizationNumber:
          description: 'Length: 6

            Authorization number

            VisionPLUS Service Data: OZXOAI-AUTH-NBR'
          example: '123'
          type: string
        effectiveAuthorizationDate:
          description: 'Length: 8

            Effective Authorization Date

            VisionPLUS Service Data: OZXOAI-EFF-DATE

            '
          format: date
          type: string
        effectiveAuthorizationTime:
          description: 'Length: 6

            Effective Authorization Time

            VisionPLUS Service Data: OZXOAI-TIME'
          example: 112233
          format: int32
          type: integer
        filter:
          description: 'Length: 1

            Filter for results.

            The values are:

            * Space or low value = All authorizations

            * A = Approved authorizations

            * D = Declined authorizations

            VisionPLUS Service Data: OZXOAI-ACTION-FILTER'
          example: A
          type: string
        foreignUseIndicator:
          description: 'Length: 1

            The FOREIGN USE indicator is provided in the input message so the requesting
            source can specify whether the request applies to the local or foreign
            account when the account is in a dual currency processing organization.

            The default is to the local account.

            The values are:

            * Zero, space, low values = Local account

            * 1 = Foreign account

            VisionPLUS Service Data: OZXOAI-FOREIGN-USE'
          example: '0'
          maxLength: 1
          maximum: 1
          minLength: 0
          minimum: 0
          type: string
        functionCode:
          description: 'Length: 1

            Function code for navigating results

            VisionPLUS Service Data: OZXOAI-SVC-FUNC-CODE'
          type: string
        numberOfAuthorizationsRequested:
          description: "Number of authorizations requested. The values are 1 through\
            \ 100. \nThe initial value is 100\nVisionPLUS Service Data: OZXOAI-NBR-OF-RECS-REQ"
          example: 100
          format: int32
          type: integer
        organizationNumber:
          description: 'Length: 3

            Organization Number'
          example: 807
          format: int32
          maximum: 999
          minimum: 1
          type: integer
      type: object
    OutstandingAuthorizationFasRequest.AuthorizationDateRange:
      properties:
        from:
          description: 'Length: 8

            Starting authorization date range.

            VisionPLUS Service Data: OZXOAI-AUTH-FROM-DATE'
          format: date
          type: string
        to:
          description: 'Length: 8

            Ending authorization date range

            VisionPLUS Service Data: OZXOAI-AUTH-TO-DATE'
          format: date
          type: string
      type: object
    OutstandingAuthorizationFasResponse:
      properties:
        accountNumber:
          description: 'Length: 19

            Account number

            VisionPLUS Service Data: OZXOAO-ACCT'
          type: string
        authorizationsData:
          items:
            $ref: '#/components/schemas/OutstandingAuthorizationFasResponse.AuthorizationData'
          type: array
        currencyCode:
          description: 'Length: 3

            Currency Code

            VisionPLUS Service Data: OZXOAO-O-CURR-NBR'
          format: int32
          type: integer
        currencyNumberOfDecimals:
          description: 'Length: 1

            Currency Number Of Decimals

            VisionPLUS Service Data: OZXOAO-O-CURR-NOD'
          format: int32
          type: integer
        foreignUseIndicator:
          description: 'Length: 1

            The FOREIGN USE indicator is provided in the input message so the requesting
            source can specify whether the request applies to the local or foreign
            account when the account is in a dual currency processing organization.

            VisionPLUS Service Data: OZXOAO-FOREIGN-USE'
          type: string
        more:
          description: 'Length: 1

            Flag indicating that more data can be obtained.

            The values are:

            * N = No

            * Y = Yes

            VisionPLUS Service Data: OZXOAO-MORE-DATA-FLAG'
          type: string
        nextToken:
          $ref: '#/components/schemas/OutstandingAuthorizationFasResponse.NextToken'
        numberOfAuthorizationsReturned:
          description: 'Length: 3

            Number Of Authorizations Returned.

            VisionPLUS Service Data: OZXOAO-NBR-RETURNED-ITEMS'
          format: int32
          type: integer
        organizationNumber:
          description: 'Length: 3

            Organization Number.

            VisionPLUS Service Data: OZXOAO-ORG'
          format: int32
          type: integer
        prevToken:
          $ref: '#/components/schemas/OutstandingAuthorizationFasResponse.PrevToken'
      type: object
    OutstandingAuthorizationFasResponse.AuthorizationData:
      properties:
        accountCurrencyCode:
          description: Account currency code
          type: string
        action:
          description: Action
          type: string
        actionReason:
          description: 'Length: 6

            Action reason'
          format: int32
          type: integer
        authorizationAmount:
          description: Authorization amount
          format: double
          type: number
        authorizationCode:
          description: Authorization code
          type: string
        authorizationResponseCode:
          description: Authorization response code
          type: string
        authorizationType:
          description: Authorization type
          type: string
        billingCurrencyCode:
          description: Billing currency code
          format: int32
          type: integer
        cardAcceptorNameAndLocation:
          description: Card acceptor name and location
          type: string
        cardNumber:
          description: Number
          type: string
        cardSequence:
          description: Card sequence
          format: int32
          type: integer
        cardholderBillingAmount:
          description: Cardholder billing amount
          type: number
        creditAvailable:
          description: Credit available
          type: number
        creditAvailableForCashAdvances:
          description: Credit available for cash advances
          type: number
        creditPlan:
          description: CreditPlan
          format: int32
          type: integer
        effectiveDate:
          description: 'Length: 8

            Effective date'
          format: date
          type: string
        localDateOfTheTransaction:
          description: Local date of the transaction
          format: date
          type: string
        localTimeOfTheTransaction:
          description: Local time of the transaction
          type: string
        logExtent:
          description: Log extent
          format: int32
          type: integer
        merchantCategoryCode:
          description: Merchant category code
          format: int32
          type: integer
        merchantCategoryCodeDescription:
          description: Merchant category code description
          type: string
        merchantCode:
          description: Merchant code
          type: string
        merchantNumber:
          description: Merchant number
          type: string
        multiWalletPrepaid:
          $ref: '#/components/schemas/OutstandingAuthorizationFasResponse.MultiWalletPrepaid'
        offeredDownPayment:
          description: Offered down payment
          type: number
        postingDate:
          description: 'Length: 8

            Posting date'
          format: date
          type: string
        processingCode:
          description: Processing code
          format: int32
          type: integer
        reasonDescription:
          description: Reason description
          type: string
        relativeByteAddress:
          description: Relative byte address
          format: int32
          type: integer
        requestType:
          description: RequestType
          type: string
        retrievalReferenceNumber:
          description: Retrieval reference number
          format: double
          type: number
        sequence:
          description: sequence
          format: int32
          type: integer
        settlementAmount:
          description: Settlement amount
          type: number
        settlementCurrencyCode:
          description: Settlement currency code
          format: int32
          type: integer
        stateOrCountry:
          description: State or country
          type: string
        systemAuditTraceNumber:
          description: System audit trace number
          type: string
        terminalNetworkName:
          description: Terminal network name
          type: string
        time:
          description: Time
          type: string
        transactionAmount:
          description: Transaction amount
          type: number
        transactionCurrencyCode:
          description: Transaction currency code
          format: int32
          type: integer
        transactionDescription:
          description: Transaction description
          type: string
        transactionEntryMode:
          description: Transaction entry mode
          format: int32
          type: integer
        transactionEntryModeDescription:
          description: Transaction entry mode description
          type: string
        transactionRecordType:
          description: Transaction record type
          format: int32
          type: integer
        transactionSourceTerminal:
          description: Transaction source terminal
          type: string
        walletFeeAmount:
          description: Wallet fee amount
          type: number
      type: object
    OutstandingAuthorizationFasResponse.FundXfrFld:
      properties:
        xfrFeeAmount:
          description: Xfr fee amount
          type: number
        xfrFromAmount:
          description: Xfr from amount
          format: int32
          type: integer
        xfrFromCurrency:
          description: Xfr from currency
          format: int32
          type: integer
        xfrToAmount:
          description: Xfr to amount
          type: number
      type: object
    OutstandingAuthorizationFasResponse.MultiWalletPrepaid:
      properties:
        atmWdrlFeeAmount:
          description: Atm wdrl fee amount
          type: number
        authWalletAmount:
          description: Auth wallet amount
          type: number
        authWalletMarkupAmount:
          description: Auth wallet markup amount
          type: number
        baseCurrencyAmount:
          description: Base currency amount
          type: number
        ccaFeeAmount:
          description: Cca fee amount
          type: number
        conversionFeeAmount:
          description: Conversion fee amount
          type: number
        crosBrdrFeeAmount:
          description: Cros brdr fee amount
          type: number
        crossWalletXfrFlag:
          description: Cross wallet xfr flag
          format: int32
          type: integer
        currencyId:
          description: Currency id
          format: int32
          type: integer
        fundXfrFld:
          $ref: '#/components/schemas/OutstandingAuthorizationFasResponse.FundXfrFld'
        ivaTaxAmount:
          description: Iva tax amount
          type: number
        walletPrstFlag:
          description: Wallet prst flag
          format: int32
          type: integer
        walletToDwltConversionRate:
          description: Wallet to dwlt conversion rate
          format: int32
          type: integer
        xfrToCurrency:
          description: Xfr to currency
          format: int32
          type: integer
      type: object
    OutstandingAuthorizationFasResponse.NextToken:
      properties:
        effectiveDate:
          description: 'Length: 7

            Field to identify the next set of records.

            VisionPLUS Service Data: OZXOAO-EFF-DATE-NEXT'
          format: date
          type: string
        extentOfTheLogFile:
          description: 'Length: 1

            Field to identify the next set of records.

            VisionPLUS Service Data: OZXOAO-ACCOUNT-LOG-EXT-NEXT'
          format: int32
          type: integer
        logRecordTypeOfTheTransaction:
          description: 'Length: 1

            Field to identify the next set of records

            VisionPLUS Service Data: OZXOAO-TXN-REC-TYPE'
          format: int32
          type: integer
        relativeByteAddress:
          description: 'Length: 9

            Field to identify the next set of records.

            VisionPLUS Service Data: OZXOAO-ACCOUNT-RBA-NEXT'
          format: int32
          type: integer
        time:
          description: 'Length: 7

            Field to identify the next set of records.

            VisionPLUS Service Data: OZXOAO-TIME-NEXT'
          type: string
      type: object
    OutstandingAuthorizationFasResponse.PrevToken:
      properties:
        effectiveDate:
          description: 'Length: 7

            Field to identify the previous set of records

            VisionPLUS Service Data: OZXOAO-EFF-DATE-PREV'
          format: date
          type: string
        extentOfTheLogFile:
          description: 'Length: 1

            Field to identify the previous set of records.

            VisionPLUS Service Data: OZXOAO-ACCOUNT-LOG-EXT-PREV'
          format: int32
          type: integer
        logRecordTypeOfTheTransaction:
          description: 'Length: 1

            Field to identify the previous set of records.

            VisionPLUS Service Data: OZXOAO-TXN-REC-TYPE-PREV'
          format: int32
          type: integer
        relativeByteAddress:
          description: 'Length: 9

            Field to identify the previous set of records.

            VisionPLUS Service Data: OZXOAO-ACCOUNT-RBA-NEXT'
          format: int32
          type: integer
        time:
          description: 'Length: 7

            Field to identify the next set of records.

            VisionPLUS Service Data: OZXOAO-TIME-NEXT'
          type: string
      type: object
info:
  description: "This documentation describes the REST APIs provided by the FirstVision\u2122\
    \ Cards Microservice, which provides functionality for the issuing, management\
    \ and processing of credit cards, including bank, co-branded, private label, debit,\
    \ commercial, and prepaid"
  title: "FirstVision\u2122 Transaction Service - API Documentation"
  version: '1.2'
openapi: 3.0.1
paths:
  /transactions/outstanding-authorizations/details:
    post:
      description: "Fetches data of both old and new transactions(including today's)\
        \ which are settled to an account. \nVMX Service: M.FAS.OUTSTANDING.AUTH.INQ,\
        \ L8V2"
      operationId: outstandingAuthorization
      parameters:
      - description: API Key
        in: header
        name: apikey
        required: true
        schema:
          type: string
      - description: Client ID
        example: 00970
        in: header
        name: X-ClientID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutstandingAuthorizationFasRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutstandingAuthorizationFasResponse'
          description: Success
        '300':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
          description: Redirection
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
          description: Backend Error
      summary: 'Outstanding Authorizations Inquiry. VMX Service: M.FAS.OUTSTANDING.AUTH.INQ,
        L8V2'
      tags:
      - Transactions
      x-group-name: Transactions
      x-proxy-name: Outstanding Authorizations Inquiry
servers:
- url: https://int.api.firstdata.com/latam-gfs-apis/portal
x-config:
  tryItOut: 'true'
