openapi: 3.0.1
info:
  title: FirstVision™ Notification Service - API Documentation
  description: Describes the message structure that will be send to the endpoint provided by the financial institution for receive events and notifications generated in FirstVision.
  version: "2.0"
tags:
- name: Notifications
  description: 'Provides notification related operations'
paths:
  /v2/pushNotification:
    post:
      tags:
        - Notifications
      x-proxy-name: Notification
      x-group-name: Notifications
      summary: |-
                Notifications for events
                - Authorization
                - Card Blocked
                - Card Activation
      operationId: Notifications v2
      parameters:
        - name: apikey
          in: header
          description: API Key
          required: true
          schema:
            type: string
            default: string
        # - name: Content-Type
        #   in: header
        #   description: Request content type
        #   schema:
        #     type: string
        #     default: application/json
      requestBody:
        description: Push Notification
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pushNotificationEventV2'
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '422':
          description: Unprocessable Entity
        '500':
          description: Backend Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PushAlertResponse'
      deprecated: false
components:
  schemas:
    pushNotificationEventV2:
      type: object
      properties:
        securityContext:
          type: string
          maxLength: 20
          example: "VMX.MULTICHANNEL.UPD"
          description:  |-
            <p>Security context.</p>
        version:
          type: string
          maxLength: 20
          example: R8V1
          description:  |-
            <p>version.</p>
        description:
          type: string
          maxLength: 40
          example: "APPROVED"
          description:  |-
            <p>Message description.</p>
        eventCode:
          type: string
          maxLength: 4
          example: "0001"
          description:  |-
            <p>SMS event code.</p>
        eventTitle:
          type: string
          maxLength: 40
          example: "TRANSACTION ALERTS"
          description:  |-
            <p>SMS event title.</p>
        eventNumber:
          type: integer
          maxLength: 2
          example: 1
          description:  |-
            <p>SMS event number.</p>
        organizationNumber:
          type: integer
          maxLength: 3
          example: 950
          description:  |-
            <p>Organization Number.</p>
        accountNumber:
          type: string
          maxLength: 19
          example: "0004513070406598974"
          description:  |-
            <p>Account Number.</p>
        customerNumber:
          type: string
          maxLength: 19
          example: "0004513070406598974"
          description:  |-
            <p>Customer number that identifies the Customer Name/Address record to which this account is assigned.</p>
        mobilePhone:
          type: string
          maxLength: 20
          example: "******9943"
          description:  |-
            <p>Mobile Phone.</p>
        emailAddress:
          type: string
          maxLength: 20
          example: "m***@d******.com"
          description:  |-
            <p>Email address.</p>
        channelType:
          type: string
          maxLength: 5
          example: "BOTH"
          description:  |-
            <p>Channel type (EMAIL, SMS, BOTH)</p>
        messageLine1:
          type: string
          maxLength: 65
          example: ""
          description:  |-
            <p>Customer Data AMNA-USER-4</p>
        messageLine2:
          type: string
          maxLength: 65
          example: ""
          description:  |-
            <p>Customer Data (SSAN) AMNA-SSAN</p>
        messageLine3:
          type: string
          maxLength: 65
          example: "******9943"
          description:  |-
            <p>Customer data Mobile Phone AMNA-MOBILE-PH</p>
        messageLine4:
          type: string
          maxLength: 65
          example: "m***@d******.com"
          description:  |-
            <p>Customer data Email AMNA-EMAIL</p>
        messageLine5:
          type: string
          maxLength: 65
          example: "294"
          description:  |-
            <p>For Authorization Event: FAS authorization action reason</p>
        messageLine6:
          type: string
          maxLength: 65
          example: "000540208ID5IXX3865"
          description:  |-
            <p>Card number(tokenized)</p>
        messageLine7:
          type: string
          maxLength: 65
          example: "00000000010.00"
          description:  |-
            <p>For Authorization Event: Transaction Amount in original currency. ISO element DE4 from authorization. For blocked card SMS the line contains block code</p>
        messageLine8:
          type: string
          maxLength: 65
          example: ""
          description:  |-
            <p>For Authorization Event: Card Acceptor Name / Merchant name ISO element DE43 from authorization</p>
            <p>For Card Blocked and Card Activation Event: Activation Flag Y = needs activation, N = Card Activated</p>
        messageLine9:
          type: string
          maxLength: 65
          example: "20220127"
          description:  |-
           <p>For Authorization Event: Authorization Date (YYYYMMDD)</p>
            <p>For Card Blocked and Card Activation Event: Date of event</p>
        messageLine10:
          type: string
          maxLength: 65
          example: "141638"
          description:  |-
            <p>For Authorization Event: Authorization Time DE12</p>
            <p>For Card Blocked and Card Activation Event: Time of event</p>
        messageLine11:
          type: string
          maxLength: 65
          example: "MXN"
          description:  |-
            <p>For Authorization Event: Transaction currency ISO element DE49 from authorization</p>
        messageLine12:
          type: string
          maxLength: 65
          example: "00 0000 00000000000000"
          description:  |-
           <p>For Authorization Event:</p>
            <p>Position 1-2 bytes : DE3 Proc code</p>
            <p>Position 3-15 bytes : DE42 Merchant ID</p>
            <p>Pos 18 - 12 bytes : DE37 reference number</p>
            <p>Pos 30 - 4 bytes : Message type ID / MTI</p>
            <p>Pos 34 - 1 bytes : FAS request type ID A : Authorization, R - reversal</p>
            <p>Pos 35 - 6 bytes : Authorization Code</p>
            <p>Pos 41 - 14 bytes : DE6 Card holder billing amount</p>
        messageLine13:
          type: string
          maxLength: 65
          example: ""
          description:  |-
            <p>User Defined</p>
        messageLine14:
          type: string
          maxLength: 65
          example: ""
          description:  |-
            <p>User Defined</p>
        messageLine15:
          type: string
          maxLength: 65
          example: "070"
          description:  |-
            <p>Short description of decline reason.</p>
            <p>070 - Card not activated.</p>
    PushAlertResponse:
      type: object
      properties:
        message:
          type: string
          maxLength: 100
          example: ""
          description:  |-
            <p>Response message</p>
        code:
          type: string
          maxLength: 20
          example: ""
          description:  |-
            <p>Response message</p>
        description:
          type: string
          maxLength: 200
          example: ""
          description:  |-
            <p>Response message</p>
