openapi: 3.0.1
info:
  title: LATAM Issuing APIs
  description: APIs to VMX Server
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licences/LICENSE-2.0
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /account/v1/installmentDetail:
    get:
      tags:
        - Account
      x-group-name: Account
      x-proxy-name: Installment Detail
      x-child-product-name: Account
      summary: 'Develop the VMX service linked to “Installment Billing Transaction Detail” that allows the issuer/Fiserv to consume data currently available in FirstVision screen ARTI03 on inquiry mode, AZXZ3S1. VMX Service: M.CMS.INSTAL.TRXN.DETAIL.INQ, L8V1'
      operationId: Installment Detail Inquiry Service
      parameters:
        - name: organizationNumber
          in: header
          description: |-
            Length: 3

            Organization number that identifies the Organization record assigned to an account.
             VisionPLUS Service Data: AZXZ3I-ORG
          required: true
          schema:
            type: integer
            format: int32
          example: 807
        - name: accountNumber
          in: header
          description: |-
            Length: 19

            The account number for which details are extracted.
             VisionPLUS Service Data: AZXZ3I-ACCT-NBR
          required: true
          schema:
            maxLength: 19
            minLength: 19
            type: string
          example: '0004349950000268001'
        - name: recordNumber
          in: query
          description: |-
            Length: 3

            Three-digit code which identifies the record number of the installment.
             VisionPLUS Service Data: AZXZ3I-REC-NBR
          required: true
          schema:
            type: integer
            format: int32
          example: 998
        - name: X-ClientID
          in: header
          description: Sign-on name.
          required: true
          schema:
            type: string
        - name: security-context
          in: header
          description: User’s sign-on in security system.
          required: false
          schema:
            type: string
        - name: username
          in: header
          description: Username for the application.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallmentDetailInquiryResponse'
        '300':
          description: Redirection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Backend Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponse'
components:
  schemas:
    DResponse:
      type: object
      properties:
        hasError:
          type: boolean
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        data:
          type: object
    Error:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    InstallmentDetailInquiryResponse:
      type: object
      properties:
        logo:
          type: integer
          description: |-
            Length: 3

            Logo of the account.

            VisionPLUS Service Data: AZXZ3O-LOGO
          format: int32
          example: 107
        installmentType:
          type: integer
          description: |-
            Length: 1

            Installment Type:
            0 – Other
            1 – Issuer
            2 – Issuer Generated
            3 – Acquirer
            4 – BNPL
            5 – Issuer Ahora
            9 – Issuer Extra
            VisionPLUS Service Data: AZXZ3O-INST-TYPE
          format: int32
          example: 1
        transactionStatus:
          type: integer
          description: |-
            Length: 1

            Status:
            0 = Active transactions that are not posted to the account.
            1 = All transactions are posted to the account;  however, not all acquirer billing transactions have been received and matched up.
            2 = Installment record pending cancellation. The cancellation activity is triggered in the immediate next daily batch run.
            3 = Installment record has been canceled.
            7 = Account transferred.
            8 = All transactions have been received and posted; 
            this record is inactive and waiting to be purged.
            9 = Record to be purged after reload
            VisionPLUS Service Data: AZXZ3O-STATUS
          format: int32
          example: 0
        statusChangedDate:
          type: string
          description: |-
            Length: 8

            Date (in ISO 8601) on which the status of this record changed.
            VisionPLUS Service Data: AZXZ3O-STATUS-CHG-DATE
          format: date
        transactionCode:
          type: integer
          description: |-
            Length: 4

            Transaction code associated with the transaction.

            VisionPLUS Service Data: AZXZ3O-TRAN-CODE
          format: int32
          example: 1441
        creditPlan:
          type: integer
          description: |-
            Length: 5

            Number that identifies the Credit Plan Master Record for the credit plan to which CMS posts this transaction

            VisionPLUS Service Data: AZXZ3O-CREDIT-PLAN
          format: int32
          example: 12121
        storeNumber:
          type: integer
          description: |-
            Length: 9

            Merchant location where the transaction originated.

            VisionPLUS Service Data: AZXZ3O-STORE-NBR
          format: int32
          example: 107080907
        annualInterestRate:
          type: number
          description: |-
            Length: 7

            Annual interest rate associated with the installment interest calculation.

            VisionPLUS Service Data: AZXZ3O-INT-RATE
          example: 11780.78
        totalTransactionAmount:
          type: number
          description: |-
            Length: 17

            Total amount of the installment billing transaction.

            VisionPLUS Service Data: AZXZ3O-TOT-TRAN-AMT
          example: 192837645517283.1
        principalAmountInstallment:
          type: number
          description: |-
            Length: 17

            Amount of principal included in the total installment billing transaction amount.

            VisionPLUS Service Data: AZXZ3O-PRINCIPAL
          example: 192837645517283.1
        installmentInterestAmount:
          type: number
          description: |-
            Length: 13

            Amount of installment interest included in the total transaction amount. 
            This field is returned only for issuer transactions.

            VisionPLUS Service Data: AZXZ3O-TOTAL-INT
          example: 19287457832.1
        membershipFeeAmount:
          type: number
          description: |-
            Length: 17

            Amount of the membership fee for the account or supplemental cards for which installments were generated. 
            This field is returned only for issuer transactions.

            VisionPLUS Service Data: AZXZ3O-TOTAL-INST-FEE
          example: 192837645517283.1
        downPaymentAmount:
          type: number
          description: |-
            Length: 17

            Amount of the down payment included in the total transaction amount. 
            This field displays only for acquirer installment transactions.

            VisionPLUS Service Data: AZXZ3O-DOWN-PMT
          example: 192837645517283.1
        airportTaxAmount:
          type: number
          description: |-
            Length: 17

            Amount of the airport tax that is included in the total transaction amount. 
            This field displays only for acquirer installment airline transactions.

            VisionPLUS Service Data: AZXZ3O-AIR-TAX
          example: 192837645517283.1
        totalInstallments:
          type: integer
          description: |-
            Length: 3

            Total number of installment billing transactions that the customer agreed to at the time of purchase.

            VisionPLUS Service Data: AZXZ3O-TOT-INST
          format: int32
          example: 109
        remainingInstallments:
          type: integer
          description: |-
            Length: 3

            Number of installment billing transactions that remain unposted to the account.

            VisionPLUS Service Data: AZXZ3O-REM-INST
          format: int32
          example: 12
        installmentPaymentAmount:
          type: number
          description: |-
            Length: 17

            Installment payment amount that includes principal and installment interest.

            VisionPLUS Service Data: AZXZ3O-INST-FIX-PMT-AMT
          example: 192837645517283.1
        internationalInstallmentAmount:
          type: number
          description: |-
            Length: 13

            U.S. dollar amount of the international installment transaction.

            VisionPLUS Service Data: AZXZ3O-ORIG-USD-AMT
          example: 19287457832.1
        internationalExchangeRate:
          type: number
          description: |-
            Length: 15

            Exchange rate used to convert the U.S. dollar amount of an international installment transaction to the currency of the ORG.

            VisionPLUS Service Data: AZXZ3O-ORIG-EXCH-USD-RATE
          example: 1928376417283.1
        effectiveTotalCost:
          type: number
          description: |-
            Length: 8

            Calculated effective annual total cost (ETC) for the issuer installment. 
            The ETC is calculated at the time of transaction authorization.

            VisionPLUS Service Data: AZXZ3O-ETC
          example: 150807.64
        totalDailyFtt:
          type: number
          description: |-
            Length: 17

            Total daily Financial Transaction Taxes (FTT) calculated for all the terms of the installment.

            VisionPLUS Service Data: AZXZ3O-TOT-DAILY-FTT
          example: 192837645517283.1
        totalAdditionalFtt:
          type: number
          description: |-
            Length: 17

            Total additional Financial Transaction Taxes (FTT) calculated for all the terms of the installment.

            VisionPLUS Service Data: AZXZ3O-ADDNL-FTT
          example: 192837645517283.1
        anticipatedDueDate:
          type: string
          description: |-
            Length: 8

            Selected date (in ISO 8601) to pay off the anticipated amount.

            VisionPLUS Service Data: AZXZ3O -ANTCP-DUE-DATE
          format: date
        anticipationAvailableAmount:
          type: number
          description: |-
            Length: 17

            Amount available for anticipation.

            VisionPLUS Service Data: AZXZ3O-ANTCP-AVL-AMT
          example: 192837645517283.1
        installmentToBeAnticipated:
          type: integer
          description: |-
            Length: 3

            Number of installments to be anticipated.

            VisionPLUS Service Data: AZXZ3O-ANTCP-NBR-INST
          format: int32
          example: 21
